### ISSUE TITLE
Expanded Row doesn't work when data length is 1

### ISSUE THREAD

**Issue by ashleyyang0610** [trendmicro-frontend/react-table#12] opened 2018-01-03 03:32 UTC
As title, when there's only 1 row in table (data array length = 1), expanded row doesn't work.

**Comment by cheton** [comment] 2018-01-03 03:41
I cannot reproduce this issue when passing data to the table with only one row. Note that you have to use unique **rowKey** to distinguish different rows.

![image](https://user-images.githubusercontent.com/447801/34508480-dd8f95b2-f07a-11e7-8af7-d025a7d60cb0.png)

**Comment by ashleyyang0610** [comment] 2018-01-03 06:50
Update finding: Expand rows feature doesn't work when rowkey is 0.

**Comment by cheton** [comment] 2018-01-03 07:42
Fixed in v0.8.3

**Closed as completed by cheton** 2018-01-03 07:42 UTC
